#!/bin/bash

# Controllers
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430149 - PXI Controllers PLP/PXI Controllers.xlsx" "controllers" "controller"

# Accessories
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/Accessories/Accessories.xlsx" "accessories" "accessory"

# Modules - all 53 types
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3206796 - Current PLP" "modules/current" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207122 - Digital IO PLP" "modules/digital_io" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207231 - Position Displacement PLP/152253 - PXI Displacement Input Module.xlsx" "modules/position_displacement" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207242 - Signal Conditioning PLP" "modules/signal_conditioning" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207252 - Sound and Vibration PLP" "modules/sound_vibration" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207255 - Strain, Pressure, and Force PLP" "modules/strain_pressure_force" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207262 - Temperature PLP" "modules/temperature" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207270 - Voltage PLP" "modules/voltage" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207283 - Digital IO Instruments PLP" "modules/digital_io_instruments" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207287 - Digital Multimeters PLP" "modules/digital_multimeters" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207291 - Electronic Load PLP" "modules/electronic_load" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207296 - Frequency Counters PLP Instruments/118734 - PXI CounterTimer Module.xlsx" "modules/frequency_counters" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207320 - LCR Meter PLP/371886 - PXI LCR Meter.xlsx" "modules/lcr_meter" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207323 - Oscilloscopes and Digitizers PLP Instruments" "modules/oscilloscopes_digitizers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207325 - Power Supplies PLP Instruments" "modules/power_supplies" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207327 - Source Measure Units PLP Instruments/118780 - PXI Source Measure Unit.xlsx" "modules/source_measure_units" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207329 - Switches PLP Instruments" "modules/switches" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207331 - Waveform Generators PLP" "modules/waveform_generators" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207333 - RF Amplifiers PLP" "modules/rf_amplifiers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207334 - Frame Grabbers PLP" "modules/frame_grabbers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207335 - Camera Interface PLP/118170 - Camera Link Adapter Module for FlexRIO.xlsx" "modules/camera_interface" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207336 - Data Storage PLP" "modules/data_storage" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207337 - Data Movement PLP" "modules/data_movement" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3207341 - Display PLP" "modules/display" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429845 - Counters and Timers PLP" "modules/counters_timers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429847 - Automotive Ethernet PLP" "modules/automotive_ethernet" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429848 - CANopen PLP" "modules/canopen" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429850 - CAN PLP" "modules/can" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429851 - LIN PLP" "modules/lin" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429852 - Serial PLP" "modules/serial" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429854 - DeviceNet PLP" "modules/devicenet" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429855 - FieldBus PLP/118300 Fieldbus Interface Device.xlsx" "modules/fieldbus" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429856 - FlexRay PLP" "modules/flexray" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429857 - GPIB PLP" "modules/gpib" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429858 - I2CSPI PLP/118326 I2CSPI Interface Device.xlsx" "modules/i2cspi" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429859 - ARINC 429 PLP/118723 PXI ARINC 429 Interface Module.xlsx" "modules/arinc_429" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429860 - ARINC 664 PLP" "modules/arinc_664" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429861 - MIL-STD-1553 PLP" "modules/mil_std_1553" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429862 - FPD-Link™ PLP/316001 PXI FlexRIO FPD-Link™ Interface Module.xlsx" "modules/fpd_link" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429864 - GMSL™ PLP/316002 - PXI FlexRIO GMSL Interface Module.xlsx" "modules/gmsl" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429865 - Ethernet PLP" "modules/ethernet" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429866 - FlexRIO Custom Instruments and Processing PLP" "modules/flexrio_custom" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429867 - Student Devices PLP" "modules/student_devices" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429868 - Engineering Lab Stations PLP" "modules/engineering_lab_stations" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429980 - Network Analyzers PLP/118787 PXI Vector Network Analyzer.xlsx" "modules/network_analyzers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3429994 - Power Sensors PLP/118813 - RF Power Sensor Device.xlsx" "modules/power_sensors" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430010 - RF Signal Generators PLP" "modules/rf_signal_generators" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430086 - RF and Microwave Switches PLP" "modules/rf_microwave_switches" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430090 - Software Defined Radios PLP" "modules/software_defined_radios" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430094 - Spectrum and Signal Analyzers PLP" "modules/spectrum_signal_analyzers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430099 - Transceivers PLP" "modules/transceivers" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430102 - System Timing" "modules/system_timing" "module"
python3 convert_excel_to_json.py "data/SW_CI_Spreadsheets/USER STORY 3430146 - FlexRIO PLP/118210 - Controller for FlexRIO.xlsx" "modules/flexrio" "module"

echo "✓ All conversions complete!"